batch_size: 4
checkpoint_path: /data3/user/yoshida/fwl_mae/neurips2026/checkpoints/paper/pruning0.7merging0.9-vit3d/vit3d_lr0.0001_timm-cosine_epoch50_div3_aug-all_v2/0505/vit3d_ordered_pruning_light_finetune_epoch_50_20260505_114728_0.03554.pth
config_name: test
device: cuda:0
divide: 1
dst_ratio_high: 0.1
encoder_depth: 6
encoder_embed_dim: 240
encoder_num_heads: 6
group_token_order: morton
ignore_visualize_labels: []
is_log: false
is_train: false
log_interval: 100
low_intensity_ratio: 0.7
low_other_logit: -20.0
low_pruning_ignore_label: -1
low_pruning_ignore_loss: true
low_unknown_logit: 20.0
merge_attn: true
merge_mlp: false
merge_ratio_high: 0.9
model_name: vit3d_ordered_pruning_light
n_channels: 1
num_classes: 4
num_workers: 4
output_dir: /home/yoshida/fw_compression/downstream/outputs/evalA_orig
patch_size:
- 20
- 8
- 4
prediction_threshold: 0.5
pruning_patch_embed_mode: sparse
pruning_patch_embed_op: conv3d
seed: 42
speed_check: false
speed_check_use_fast_label_path: true
target_size:
- 200
- 168
- 300
test_annotation_dirs:
- /data3/user/ikeda/ghost_dataset/36build/annotation_v1_expand/hist002
- /data3/user/ikeda/ghost_dataset/36build/annotation_v1_expand/hist003
- /data3/user/ikeda/ghost_dataset/36build/annotation_v1_expand/hist004
- /data3/user/ikeda/ghost_dataset/36build/annotation_v1_expand/hist005
- /data3/user/ikeda/ghost_dataset/36build/annotation_v1_expand/hist006
- /data3/user/ikeda/ghost_dataset/36build/annotation_v1_expand/hist007
- /data3/user/ikeda/ghost_dataset/36build/annotation_v1_expand/hist008
- /data3/user/ikeda/ghost_dataset/36build/annotation_v1_expand/hist009
- /data3/user/ikeda/ghost_dataset/36build/annotation_v1_expand/hist010
- /data3/user/ikeda/ghost_dataset/36build/annotation_v1_expand/hist011
- /data3/user/ikeda/ghost_dataset/22build/annotation_v1_expand/hist001
- /data3/user/ikeda/ghost_dataset/22build/annotation_v1_expand/hist002
- /data3/user/ikeda/ghost_dataset/22build/annotation_v1_expand/hist003
- /data3/user/ikeda/ghost_dataset/22build/annotation_v1_expand/hist004
- /data3/user/ikeda/ghost_dataset/22build/annotation_v1_expand/hist005
- /data3/user/ikeda/ghost_dataset/22build/annotation_v1_expand/hist006
- /data3/user/ikeda/ghost_dataset/22build/annotation_v1_expand/hist007
- /data3/user/ikeda/ghost_dataset/22build/annotation_v1_expand/hist008
- /data3/user/ikeda/ghost_dataset/22build/annotation_v1_expand/hist009
- /data3/user/ikeda/ghost_dataset/22build/annotation_v1_expand/hist010
- /data3/user/ikeda/ghost_dataset/14build_7floor/annotation_v1_expand/hist001
- /data3/user/ikeda/ghost_dataset/14build_7floor/annotation_v1_expand/hist002
- /data3/user/ikeda/ghost_dataset/14build_7floor/annotation_v1_expand/hist003
- /data3/user/ikeda/ghost_dataset/14build_7floor/annotation_v1_expand/hist004
- /data3/user/ikeda/ghost_dataset/14build_7floor/annotation_v1_expand/hist005
- /data3/user/ikeda/ghost_dataset/14build_7floor/annotation_v1_expand/hist006
- /data3/user/ikeda/ghost_dataset/14build_7floor/annotation_v1_expand/hist007
- /data3/user/ikeda/ghost_dataset/14build_7floor/annotation_v1_expand/hist008
- /data3/user/ikeda/ghost_dataset/14build_7floor/annotation_v1_expand/hist009
- /data3/user/ikeda/ghost_dataset/14build_7floor/annotation_v1_expand/hist010
test_voxel_dirs:
- /data3/user/ikeda/ghost_dataset/36build/data/hist002
- /data3/user/ikeda/ghost_dataset/36build/data/hist003
- /data3/user/ikeda/ghost_dataset/36build/data/hist004
- /data3/user/ikeda/ghost_dataset/36build/data/hist005
- /data3/user/ikeda/ghost_dataset/36build/data/hist006
- /data3/user/ikeda/ghost_dataset/36build/data/hist007
- /data3/user/ikeda/ghost_dataset/36build/data/hist008
- /data3/user/ikeda/ghost_dataset/36build/data/hist009
- /data3/user/ikeda/ghost_dataset/36build/data/hist010
- /data3/user/ikeda/ghost_dataset/36build/data/hist011
- /data3/user/ikeda/ghost_dataset/22build/data/hist001
- /data3/user/ikeda/ghost_dataset/22build/data/hist002
- /data3/user/ikeda/ghost_dataset/22build/data/hist003
- /data3/user/ikeda/ghost_dataset/22build/data/hist004
- /data3/user/ikeda/ghost_dataset/22build/data/hist005
- /data3/user/ikeda/ghost_dataset/22build/data/hist006
- /data3/user/ikeda/ghost_dataset/22build/data/hist007
- /data3/user/ikeda/ghost_dataset/22build/data/hist008
- /data3/user/ikeda/ghost_dataset/22build/data/hist009
- /data3/user/ikeda/ghost_dataset/22build/data/hist010
- /data3/user/ikeda/ghost_dataset/14build_7floor/data/hist001
- /data3/user/ikeda/ghost_dataset/14build_7floor/data/hist002
- /data3/user/ikeda/ghost_dataset/14build_7floor/data/hist003
- /data3/user/ikeda/ghost_dataset/14build_7floor/data/hist004
- /data3/user/ikeda/ghost_dataset/14build_7floor/data/hist005
- /data3/user/ikeda/ghost_dataset/14build_7floor/data/hist006
- /data3/user/ikeda/ghost_dataset/14build_7floor/data/hist007
- /data3/user/ikeda/ghost_dataset/14build_7floor/data/hist008
- /data3/user/ikeda/ghost_dataset/14build_7floor/data/hist009
- /data3/user/ikeda/ghost_dataset/14build_7floor/data/hist010
use_threshold_prediction: true
y_crop_bottom: 88
y_crop_top: 88
z_crop_back: 375
z_crop_front: 25
